version: '2'
services:
  e2e:
    image: cypress
    build: .
    container_name: cypress-test
    command: npx cypress run
 jenkins:
  container_name: jenkins
  build: "jenkins/"
  ports:
    - "8080:8080"
  environment:
    - JAVA_OPTS:-Djava.awt.headless=true
  volumes:
    - /var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
