version: '2'
services:
  e2e:
    image: cypress
    build: .
    container_name: cypress-test
    command: npx cypress run
    volumes:
    - /var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
