#app.gocd.yml
format_version: 2
pipelines:
 CypressMonitoring:
   group: pss
   materials:
     source:
       type: configrepo
       destination: source
   stages:
   - UI:
      jobs:
         Test:
           elastic_profile_id: "cypress"
           tasks:
           - exec:
               working_directory: source
               run_if: passed
               command: "sh"
               arguments: ["-c", "test.sh"]
        